config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Attachinary::Engine => "/attachinary"

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # resources :fundraisers, only: [:index, :new, :create, :show, :edit, :update] do
  #   resources :direct_donations, only: [:index, :new, :create, :show, :edit, :update]
  #   resources :events, only: [:index, :new, :create, :show, :edit, :update] do
  #     resources :event_donations, only: [:new, :create, :show]
  #   end
  # end

  resources :fundraisers, only: [:index, :new, :create, :show, :edit, :update] do
    resources :fundraiser_updates, except: [:index]
    resources :fundraiser_videos, except: [:index, :show]
    resources :direct_donations, only: [:index, :new, :create, :show]
    resources :offline_donations, except: [:index, :show]
    resources :events do
      delete "/fundraisers/:fundraiser_id/events/:id", to: "events#destroy", as: "event_destroy"
      resources :event_donations, only: [:new, :create, :show]
      resources :event_videos, except: [:index, :show]
      resources :event_updates, except: [:index]
      resources :offline_donations, except: [:index, :show]
    end
  end

  resources :charities, except: [:destroy]
  get "about_us", to: 'pages#about_us'
  get "help", to: 'pages#help'
  get "contact_us", to: 'pages#contact_us'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/charity.rb
class Charity < ApplicationRecord
  belongs_to :user
  has_attachments :photos, maximum: 5

  def total_raised
    self.amount_raised = 0
    self.user.fundraisers.each { |fundraiser| self.amount_raised += fundraiser.total_raised unless fundraiser.total_raised.nil? }
    self.amount_raised
  end

  def number_donations
    no_donations = 0
    self.user.fundraisers.each do  |fundraiser|
      no_donations += fundraiser.direct_donations.count
      fundraiser.events.each { |event| no_donations += event.event_donations.count }
    end
    no_donations
  end

end

app/models/direct_donation.rb
class DirectDonation < ApplicationRecord
  belongs_to :user
  belongs_to :fundraiser
end

app/models/direct_dontation.rb
class DirectDontation < ApplicationRecord
  belongs_to :user
  belongs_to :fundraising_event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  belongs_to :fundraiser
  validates :target, presence: true
  has_many :event_donations
  has_many :event_videos
  has_many :event_updates
  has_many :offline_donations, as: :imageable
  has_attachments :photos, maximum: 5


  def total_raised
    self.amount_raised = 0
    self.event_donations.each { |donation| self.amount_raised += donation.amount }
    self.offline_donations.each { |donation| self.amount_raised += donation.amount}
    self.amount_raised
  end

end

app/models/event_donation.rb
class EventDonation < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event_update.rb
class EventUpdate < ApplicationRecord
  belongs_to :event
  has_attachments :photos, maximum: 5

  def video_url
    url = self.link.split("v=")[1]
    return url
  end

end

app/models/event_video.rb
class EventVideo < ApplicationRecord
  belongs_to :event

  def video_url
    url = self.link.split("v=")[1]
    return url
  end

end

app/models/fundraiser.rb
class Fundraiser < ApplicationRecord
  belongs_to :user
  has_many :events
  has_many :direct_donations
  has_many :fundraiser_videos
  has_many :fundraiser_updates
  has_many :offline_donations, as: :imageable
  validates :goal, inclusion: { in: ['Raise Money', 'Find Volunteers'], message: "%{value} is not a valid selection" }
  validates :label, inclusion: { in: ['People', 'Planet', 'Dignity'], message: "%{value} is not a valid selection" }
  has_attachments :photos, maximum: 5

  #has_many :event_donations, through: :event

  def total_raised
    self.amount_raised = 0
    self.direct_donations.each { |donation| self.amount_raised += donation.amount }
    self.offline_donations.each { |donation| self.amount_raised += donation.amount }
    self.events.each { |event| self.amount_raised += event.total_raised }
    self.amount_raised
  end

end

app/models/fundraiser_update.rb
class FundraiserUpdate < ApplicationRecord
  belongs_to :fundraiser
  has_attachments :photos, maximum: 5


  def video_url
    url = self.link.split("v=")[1]
    return url
  end

end

app/models/fundraiser_video.rb
class FundraiserVideo < ApplicationRecord
  belongs_to :fundraiser


  def video_url
    url = self.link.split("v=")[1]
    return url
  end


end

app/models/fundraising_event.rb
class FundraisingEvent < ApplicationRecord
  belongs_to :user
  has_many :events
  has_many :direct_donations
  has_many :event_donations, through: :event
end

app/models/offline_donation.rb
class OfflineDonation < ApplicationRecord
  belongs_to :imageable, polymorphic: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :event_donations
  has_many :direct_donations
  has_many :events
  has_many :fundraisers
  has_one :charity

  after_create :send_welcome_email

  devise :omniauthable, omniauth_providers: [:facebook]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params[:friend_uids] = auth.extra.raw_info.friends.data.map(&:id) if !auth.extra.raw_info.friends.data.nil?
    user_params = user_params.to_h

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end


  private

  def send_welcome_email
    UserMailer.welcome(self).deliver_now
  end

end

app/models/volunteer.rb
class Volunteer < ApplicationRecord
  belongs_to :user
end

app/controllers/fundraisers_controller.rb
class FundraisersController < ApplicationController
  before_action :set_fundraiser, only: [:show, :edit, :update]

  def index
    @fundraisers = policy_scope(Fundraiser).order(:updated_at)
    authorize @fundraisers
  end

  def new
    @fundraiser = Fundraiser.new
    authorize @fundraiser
  end

  def create
    @fundraiser = Fundraiser.create(fundraiser_params)
    @fundraiser.user = current_user
    authorize @fundraiser

    if @fundraiser.save
      redirect_to fundraiser_path(@fundraiser)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update

    if @fundraiser.update(fundraiser_params)
      redirect_to fundraiser_path(@fundraiser)
    else
      render :new
    end
  end

  def destroy
  end

  private

  def set_fundraiser
    @fundraiser = Fundraiser.find(params[:id])
    authorize @fundraiser
  end

  def fundraiser_params
    params.require(:fundraiser).permit(:user_id, :goal, :title, :target, :end_date, photos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charitys_helper.rb
module CharitysHelper
end

app/helpers/event_videos_helper.rb
module EventVideosHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/fundraisers_helper.rb
module FundraisersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/volunteer_helper.rb
module VolunteerHelper
end

app/views/fundraisers/_form.html.erb
<div class="form-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-4 col-sm-offset-4">

        <div class="form-box">
          <%= simple_form_for @fundraiser do |f| %>

            <%= f.input :title %>
            <%= f.input :goal, label: :Goal, collection: ['Save lives', 'Alleviate Poverty', 'Nature Protection'], default: 'Save lives' %>
            <%= f.input :target %>
            <%= f.input :end_date %>
            <%= f.input :photos, as: :attachinary %>

            <%= f.submit %>

          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/fundraisers/index.html.erb
<div class="container">

  <% @fundraisers.each do |fundraiser| %>
      <div class="row thin-header index-page">
          <!-- card -->
          <div class="col-xs-4">
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image_path 'library/crowd.jpg' %>');">
            </div>
          </div>


          <!-- Body of Text -->
          <div class="col-xs-6">
            <h2> <%= fundraiser.title %> (title of fundraiser) </h2>
            <h3> <%= fundraiser.user.charity.name %> (name of charity) </h3>
            <h4> Insert aim of fundraiser here </h4>
          </div>

          <!-- Amount fundraised + friends -->
          <div class="col-xs-2">
            <span class="off-complimentary">£<%= fundraiser.total_raised.ceil %></span> of <span class="off-complimentary">£<%= fundraiser.target.ceil %></span> raised
            <div id="donor_counter"></div>
            <p> Facebook friends etx </p>
            <% if user_signed_in? %>

              <!-- Events hosted by friends -->
              <% fundraiser.events.each do |event| %>

                <% if current_user.friend_uids.include?(event.user.uid) %>
                  Your friend <%= event.user.first_name %> is hosting <%= link_to event.title, fundraiser_event_path(fundraiser, event) %>
                <% end %>

                <!-- Donations made by friends to events -->
                <% event.event_donations.each do |donation| %>
                  <% if current_user.friend_uids.include?(donation.user.uid) %>
                    Your friend <%= donation.user.first_name %> donated to <%= link_to event.title, fundraiser_event_path(fundraiser, event) %> in this fundraiser
                  <% end %>
                <% end %>

              <% end %>

              <!-- Donations made by friends to fundraisers -->
              <% fundraiser.direct_donations.each do |donation| %>
                <% if current_user.friend_uids.include?(donation.user.uid) %>
                  Your friend <%= donation.user.first_name %> donated to this fundraiser
                <% end %>
              <% end %>

            <% end %>
          </div>

        <%= link_to "", fundraiser_path(fundraiser), class: "card-link" %>
      </div>
  <% end %>
</div>

app/views/fundraisers/show.html.erb
<div class="container">

  <div class="row" style="border-bottom: 1px solid #800020; padding-bottom: 30px;">
    <h1 class="thin-header"> </h1>

    <!-- basic information -->
    <!-- <div class="section-seperator"> -->
      <h1>
        <%= link_to @fundraiser.user.charity.name, charity_path(@fundraiser.user.charity) %> : <%= @fundraiser.title %>
      </h1>
      <h3 style="margin: 0"> Help <%= @fundraiser.goal %> today </h3>

    <div class="col-xs-12 col-md-6" style="padding-top: 30px">
        <%= image_tag "library/baby.jpg", class: "half-page-image" %>
    </div>

    <div class="col-xs-12 col-md-6">
      <!-- basic information -->
      <div>
        <h2>
          <span class="off-complimentary">£<%= @fundraiser.total_raised.ceil %></span> of <span class="off-complimentary">£<%= @fundraiser.target.ceil %></span> raised so far
        </h2>
        <h2>
        </h2>
        <% unless @fundraiser.end_date.nil? %>
        <h5>Ending <%= @fundraiser.end_date.strftime("%e %B %Y") %></h5>
        <% end %>
        <div id="donor_counter"></div>
        <div class="text-center">
        <br>
        <br>
         <button type="button" class="big-button btn btn-lg hvr-grow" data-toggle="modal" data-target="#donateModal">Donate</button>
        </div>
      </div>
    </div>

  </div>

  <div class="modal fade" id="donateModal" tabindex="-1" role="dialog" aria-labelledby="donateModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="donateModalLabel">Donate</h4>
        </div>
        <!-- direct donations -->
        <div class="modal-body">
          <%= render 'direct_donations/form', fundraiser: @fundraiser, direct_donation: DirectDonation.new %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

  <!-- OFFLINE DONATIONS -->
  <div class="row underlined" style="padding-bottom: 20px">
    <div class="col-xs-12 col-md-6">
      <div class="some-padding">
        <h2 class="brand-color" style="font-weight: lighter" >Offline Donations <i class="fa fa-question-circle-o" style="font-size: 25px" aria-hidden="true" data-toggle="tooltip" data-placement="right" title="Donations given outside Group Action"></i></h2>
        <!-- if page owner can create/edit offline donations -->
        <% if @fundraiser.user == current_user %>
          <%= link_to "Record an offline donation", new_fundraiser_offline_donation_path(@fundraiser), class: "btn btn-primary", style: "margin-bottom: 15px" %>
        <% end %>
      <!-- total raised (shitty formula I know) -->
        <% fundraiser_offline_donation = 0 %>
        <p style="font-size: 20px"> Total raised offline: <% @fundraiser.offline_donations.each do |donation| %>
          <% fundraiser_offline_donation += donation.amount %>
          <% end %>
          <span style="color: #BD2F53">£<%= fundraiser_offline_donation.ceil %></span>
        </p>
      <!-- offline donation comments -->
          <h3 style="font-weight: lighter; color: #800020">Previous offline donations</h3>
          <% @fundraiser.offline_donations.each do |donation| %>
            <p> <span class="bold-off-brand">£<%= donation.amount.ceil %></span> | <%= donation.message %>
            <% if @fundraiser.user == current_user %>
              <span class="float-right opacity-link">
                <%= link_to "edit", edit_fundraiser_offline_donation_path(@fundraiser, donation) %> |
                <%= link_to "delete", fundraiser_offline_donation_path(@fundraiser, donation), data: { confirm: "Are you sure?" }, method: :delete %>
              </span>
            <% end %>
            </p>
          <% end %>
      </div>
    </div>

    <!-- PREVIOUS DIRECT DONATIONS -->
    <div class="col-cs-12 col-md-6">
      <div>
        <h2 class="brand-color" style="font-weight: lighter">Previous donations</h2>
          <% @fundraiser.direct_donations.each do |donation| %>
          <% if (donation.message == "")
              message = "no message"
            else
              message = donation.message
           end %>
           <p><span class="bold-off-brand">£<%= donation.amount.ceil %></span> <span class="off-complimentary" style="font-weight: bolder"> | <%= donation.created_at.strftime('%e %B') %> | </span> <%= message %> </p>
          <% end %>
      </div>
    </div>

  </div>

  <!-- youtube videos -->

  <div class="row underlined" style="padding-bottom: 20px">

    <div class="col-xs-12">
      <h1 class="brand-color" style="font-weight: lighter">Videos and pictures</h1>
      <!-- If owner of the fundraiser add a video -->
      <% if @fundraiser.user == current_user %>
        <%= link_to "Add a new video", new_fundraiser_fundraiser_video_path(@fundraiser), class: "btn btn-primary" %>
      <% end %>

      <div class="row">
        <% @fundraiser.fundraiser_videos.each do |video| %>
          <div class="col-sm-6">
            <h3 class="opacity-link"> <%=  video.title  %> <%= link_to edit_fundraiser_fundraiser_video_path(@fundraiser, video) do %>
              <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
            <% end %>
            <%= link_to fundraiser_fundraiser_video_path(@fundraiser, video), method: 'delete', :data => {:confirm => 'Are you sure?'} do %>
               <i class="fa fa-trash-o" aria-hidden="true"></i>
            <% end %> </h3>
            <div class="video-wrapper">
              <iframe id="ytplayer" type="text/html" width="560" height="349"
          src="https://www.youtube.com/embed/<%=video.video_url%>?autoplay=0&origin=http://example.com"
          frameborder="0"></iframe>
            </div>
          </div>
        <% end %>


                 <!-- photos v2 -->
          <div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls">
              <div class="slides"> </div>
              <h3 class="title"></h3>
              <a class="prev">‹</a>
              <a class="next">›</a>
              <a class="close">×</a>
              <a class="play-pause"></a>
              <ol class="indicator"></ol>
          </div>

          <div id="links col-sm-6">
              <% @fundraiser.photos.each do |photo| %>
                <%= link_to cl_image_path photo.path do %>
                  <%= cl_image_tag photo.path, width: 300, crop: :fill, class: "gallery-image"%>
                <% end %>
              <% end %>
          </div>


        </div>
      </div>
    </div>


    <!-- Updates! -->
  <div class="row underlined" style="padding-bottom: 20px">
    <div class="col-xs-12">
      <h1 class="brand-color" style="font-weight: lighter">News</h1>
      <% @fundraiser.fundraiser_updates.each do |update| %>
        <div class="row">
          <div class="col-sm-6">
            <h2 class="opacity-link">
            <%= update.title %>  <%= link_to edit_fundraiser_fundraiser_update_path(@fundraiser, update) do %>
              <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
            <% end %>
            <%= link_to fundraiser_fundraiser_update_path(@fundraiser, update), method: 'delete', :data => {:confirm => 'Are you sure?'} do %>
              <i class="fa fa-trash-o" aria-hidden="true"></i>
            <% end %>
            </h2>
          </div>
          <div class="col-sm-6">
            <p> <%= update.message.truncate_words(40) %> <%= link_to "read more...", fundraiser_fundraiser_update_path(@fundraiser, update)  %></p>
          </div>
        </div>
      <% end %>

      <!-- If ownder of the fundraiser add an update -->
      <% if @fundraiser.user == current_user %>
      <%= link_to "Add a new update", new_fundraiser_fundraiser_update_path(@fundraiser), class: "btn btn-primary" %>
    <% end %>
    </div>
  </div>

<!-- Events for the fundraiser -->
  <div class="row underlined" style="padding-bottom: 20px">
    <div class="col-xs-12">
      <h1 class="brand-color" style="font-weight: lighter">Events for the Fundraiser</h1>
        <%= link_to "Create event", new_fundraiser_event_path(@fundraiser), class: "btn btn-primary" %>
      <% @fundraiser.events.each do |event| %>
        <div class="col-xs-12 col-sm-6">
          <div class="white-box">
            <div>
              <%= cl_image_tag event.photos.first.path, class: "thumbnail-img " unless event.photos.first.nil? %>
            </div>
            <div style="display: flex; flex-direction: column; justify-content: space-between; padding-left: 20px" class="opacity-link">
              <%= link_to event.title, fundraiser_event_path(@fundraiser, event)  %>
              <p>Total raised: <span class="bold-off-brand">£<%= event.total_raised.ceil %></span> </p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>


  </div>

</div> <!-- end of container -->

<%= content_for(:after_js) do %>
  <script>
    $(document).ready(function(){
      $('#donor_counter').goalProgress({
        goalAmount: <%= @fundraiser.target %>,
        currentAmount: <%= @fundraiser.total_raised %>,
        textBefore: '£',
        textAfter: ' raised'
      });
      $(function () {
        $('[data-toggle="tooltip"]').tooltip()
      })
    });
  </script>

  <script>
  document.getElementById('links col-sm-6').onclick = function (event) {
      event = event || window.event;
      var target = event.target || event.srcElement,
          link = target.src ? target.parentNode : target,
          options = {index: link, event: event},
          links = this.getElementsByTagName('a');
      blueimp.Gallery(links, options);
  };
  </script>



<% end %>