config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Attachinary::Engine => "/attachinary"

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # resources :fundraisers, only: [:index, :new, :create, :show, :edit, :update] do
  #   resources :direct_donations, only: [:index, :new, :create, :show, :edit, :update]
  #   resources :events, only: [:index, :new, :create, :show, :edit, :update] do
  #     resources :event_donations, only: [:new, :create, :show]
  #   end
  # end

  resources :fundraisers, only: [:index, :new, :create, :show, :edit, :update] do
    resources :fundraiser_updates, except: [:index]
    resources :fundraiser_videos, except: [:index, :show]
    resources :direct_donations, only: [:index, :new, :create, :show]
    resources :offline_donations, except: [:index, :show]
    resources :events do
      delete "/fundraisers/:fundraiser_id/events/:id", to: "events#destroy", as: "event_destroy"
      resources :event_donations, only: [:new, :create, :show]
      resources :event_videos, except: [:index, :show]
      resources :event_updates, except: [:index]
      resources :offline_donations, except: [:index, :show]
    end
  end

  resources :charities, except: [:destroy]
  get "about_us", to: 'pages#about_us'
  get "help", to: 'pages#help'
  get "contact_us", to: 'pages#contact_us'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/charity.rb
class Charity < ApplicationRecord
  belongs_to :user
  has_attachments :photos, maximum: 5

  def total_raised
    self.amount_raised = 0
    self.user.fundraisers.each { |fundraiser| self.amount_raised += fundraiser.total_raised unless fundraiser.total_raised.nil? }
    self.amount_raised
  end

  def number_donations
    no_donations = 0
    self.user.fundraisers.each do  |fundraiser|
      no_donations += fundraiser.direct_donations.count
      fundraiser.events.each { |event| no_donations += event.event_donations.count }
    end
    no_donations
  end

end

app/models/direct_donation.rb
class DirectDonation < ApplicationRecord
  belongs_to :user
  belongs_to :fundraiser
end

app/models/direct_dontation.rb
class DirectDontation < ApplicationRecord
  belongs_to :user
  belongs_to :fundraising_event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  belongs_to :fundraiser
  validates :target, presence: true
  has_many :event_donations
  has_many :event_videos
  has_many :event_updates
  has_many :offline_donations, as: :imageable
  has_attachments :photos, maximum: 5


  def total_raised
    self.amount_raised = 0
    self.event_donations.each { |donation| self.amount_raised += donation.amount }
    self.offline_donations.each { |donation| self.amount_raised += donation.amount}
    self.amount_raised
  end

end

app/models/event_donation.rb
class EventDonation < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event_update.rb
class EventUpdate < ApplicationRecord
  belongs_to :event
  has_attachments :photos, maximum: 5

  def video_url
    url = self.link.split("v=")[1]
    return url
  end

end

app/models/event_video.rb
class EventVideo < ApplicationRecord
  belongs_to :event

  def video_url
    url = self.link.split("v=")[1]
    return url
  end

end

app/models/fundraiser.rb
class Fundraiser < ApplicationRecord
  belongs_to :user
  has_many :events
  has_many :direct_donations
  has_many :fundraiser_videos
  has_many :fundraiser_updates
  has_many :offline_donations, as: :imageable
  validates :goal, inclusion: { in: ['Raise Money', 'Find Volunteers'], message: "%{value} is not a valid selection" }
  validates :label, inclusion: { in: ['People', 'Planet', 'Dignity'], message: "%{value} is not a valid selection" }
  has_attachments :photos, maximum: 5

  #has_many :event_donations, through: :event

  def total_raised
    self.amount_raised = 0
    self.direct_donations.each { |donation| self.amount_raised += donation.amount }
    self.offline_donations.each { |donation| self.amount_raised += donation.amount }
    self.events.each { |event| self.amount_raised += event.total_raised }
    self.amount_raised
  end

end

app/models/fundraiser_update.rb
class FundraiserUpdate < ApplicationRecord
  belongs_to :fundraiser
  has_attachments :photos, maximum: 5


  def video_url
    url = self.link.split("v=")[1]
    return url
  end

end

app/models/fundraiser_video.rb
class FundraiserVideo < ApplicationRecord
  belongs_to :fundraiser


  def video_url
    url = self.link.split("v=")[1]
    return url
  end


end

app/models/fundraising_event.rb
class FundraisingEvent < ApplicationRecord
  belongs_to :user
  has_many :events
  has_many :direct_donations
  has_many :event_donations, through: :event
end

app/models/offline_donation.rb
class OfflineDonation < ApplicationRecord
  belongs_to :imageable, polymorphic: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :event_donations
  has_many :direct_donations
  has_many :events
  has_many :fundraisers
  has_one :charity

  after_create :send_welcome_email

  devise :omniauthable, omniauth_providers: [:facebook]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params[:friend_uids] = auth.extra.raw_info.friends.data.map(&:id) if !auth.extra.raw_info.friends.data.nil?
    user_params = user_params.to_h

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end


  private

  def send_welcome_email
    UserMailer.welcome(self).deliver_now
  end

end

app/models/volunteer.rb
class Volunteer < ApplicationRecord
  belongs_to :user
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charitys_helper.rb
module CharitysHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/volunteer_helper.rb
module VolunteerHelper
end

app/views/shared/_error_messages.html.erb
 <% if object.errors.any? %>
  <div id="error_explanation">
   <div class="alert alert-error">
     The form contains <%= pluralize(object.errors.count, "error") %>.
   </div>
  <ul>
   <% object.errors.full_messages.each do |msg| %>
    <li>* <%= msg %></li>
   <% end %>
 </ul>
</div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-items">
    <div class="footer-icon">
      <%= link_to "" do %>
      <i class="fa fa-facebook" aria-hidden="true"></i>
      <% end %>
    </div>
      <div class="footer-icon">
      <%= link_to "" do %>
      <i class="fa fa-instagram" aria-hidden="true"></i>
      <% end %>
    </div>
        <div class="footer-icon">
    <%= link_to "" do %>
      <i class="fa fa-twitter" aria-hidden="true"></i>
      <% end %>
    </div>

    </div>

  <div class="footer-items">

    <div class="item">
      <%= link_to "Our Charities", charities_path, class: "footer_link" %>
    </div>



    <div class="item">
      <%= link_to "about us", about_us_path, class: "footer_link" %>
    </div>
    <div class="item">
      <%= link_to "help", help_path, class: "footer_link" %>
    </div>
    <div class="item">
      <%= link_to "contact us", contact_us_path, class: "footer_link" %>
    </div>
  </div>
</div>

app/views/shared/_home_navbar.html.erb
<div id ="home-navbar">

  <div id="home-nav-left">

      <!-- charities to be able to see other charities & ongoing fundraisers on left of screen -->
  </div>


  <!-- notifications tab for signed in admin -->
  <p>
    <% if user_signed_in? && current_user.admin == true && User.where(is_charity: true, verified: false).count > 0 %>
        <%= link_to "There are #{User.where(is_charity: true, verified: false).count} users to verify", rails_admin_path, class: "home-sign-up-btn btn text-center"%>
    <% end %>
  </p>

  <div id="home-nav-right">

      <!-- if signed in -->
  <% if user_signed_in? %>
      <!-- non-charity-user to see affiliated charities & fundraisers -->
    <% if !current_user.is_charity  %>
      <%= link_to "See our Affiliated Charities", charities_path, class: "home-sign-up-btn btn text-center" %>
      <%= link_to "See Fundraisers", fundraisers_path, class: "home-sign-up-btn btn text-center" %>
    <% end %>

  <!-- Charity user to create your charity/manage your charity -->
    <% if current_user.is_charity && current_user.verified && current_user.charity.nil? %>
        <%= link_to "Create Your Charity", new_charity_path, class: "home-sign-up-btn btn text-center" %>
    <% elsif current_user.is_charity && current_user.verified  %>
      <%= link_to "Manage Your Charity", charity_path(current_user.charity), class: "home-sign-up-btn btn text-center" %>
      <%= link_to "Create a fundraiser", new_fundraiser_path, class: "home-sign-up-btn btn text-center"%>
    <% end %>

  <!-- sign out -->
      <%= link_to "log out", destroy_user_session_path, method: :delete, class: "home-sign-up-btn btn text-center" %>
  <% end %>



<!-- not signed in to sign up (as a user) or log in -->
    <% if !user_signed_in? %>
      <%= link_to t(".sign_in", default: "Sign up"), new_user_registration_path(is_charity: false), class: "home-sign-up-btn btn text-center" %>
      <%= link_to t(".sign_in", default: "Log in"), new_user_session_path, class: "home-sign-up-btn btn text-center" %>
    <% end %>

  <!-- end of home-nav-right -->
  </div>

<!-- end of navbar -->
</div>

<% content_for(:after_js) do %>
  <script>
    var mywindow = $(window);
    var mypos = mywindow.scrollTop();
    mywindow.scroll(function() {
      if <% !user_signed_in? %> {
        if(mywindow.scrollTop() > mypos)
        {
            $('#home-navbar').fadeOut();
        }
        else
        {
            $('#home-navbar').fadeIn();
        }
        mypos = mywindow.scrollTop();
      }
   });
  </script>
<% end %>

app/views/shared/_navbar.html.erb
<div class="ga-navbar">

<div class="ga-nav-right">
  <div class="nav-logo">
    <%= link_to root_path, class: "small-nav-logo" do %>
      <%= image_tag "dark-globe-logo.png" %>
    <% end %>
  </div>


  <!-- charities to be able to see other charities & ongoing fundraisers on left of screen -->
  <div>
    <% if user_signed_in? %>
    <% if current_user.is_charity%>
      <%= link_to "See our Affiliated Charities", charities_path, class: "" %>
      <%= link_to "See Fundraisers", fundraisers_path, class: "" %>
    <% end %>
  <% end %>
  </div>


</div>

  <!-- notifications tab -->
  <p>
    <% if user_signed_in? && current_user.admin && User.where(is_charity: true, verified: false).count > 0 %>
        <%= link_to "There are #{User.where(is_charity: true, verified: false).count} users to verify", rails_admin_path, class: ""%>
    <% end %>
  </p>

  <div class="ga-nav-right">

    <% if user_signed_in? %>
      <!-- non-charity-user to see affiliated charities & fundraisers -->
    <% if !current_user.is_charity  %>
      <%= link_to "See our Affiliated Charities", charities_path, class: "" %>
      <%= link_to "See Fundraisers", fundraisers_path, class: "" %>
    <% end %>

  <!-- Charity user to create your charity/manage your charity -->
    <% if current_user.is_charity && current_user.verified && current_user.charity.nil? %>
        <%= link_to "Create Your Charity", new_charity_path, class: "" %>
    <% elsif current_user.is_charity && current_user.verified  %>
      <%= link_to "Manage Your Charity", charity_path(current_user.charity), class: "" %>
      <%= link_to "Create a fundraiser", new_fundraiser_path, class: ""%>
    <% end %>

  <!-- sign out -->
      <%= link_to "log out", destroy_user_session_path, method: :delete, class: "" %>
  <% end %>



<!-- not signed in to sign up (as a user) or log in -->
    <% if !user_signed_in? %>
      <%= link_to t(".sign_in", default: "Sign up"), new_user_registration_path(is_charity: false), class: "" %>
      <%= link_to t(".sign_in", default: "Log in"), new_user_session_path, class: "" %>
    <% end %>

<!-- end of navbar right -->
  </div>

</div>

app/views/shared/_old_navbar.html.erb
<div class="GroupAction-navbar" id="hover-nav">


  <!-- left side of navbar -->
  <div class="left-side-navbar">

    <div class="navbar-GroupAction-sides no-wrap">
    <div>
      <% if !user_signed_in? %>
        <div class="sign-up-btn">
          <%= link_to t(".sign_in", default: "Sign up as a Charity"), new_user_registration_path(is_charity: true), class: "navbar-GroupAction-item-item navbar-GroupAction-item-link hvr-grow" %>
        </div>
      <% elsif current_user.is_charity? && current_user.verified? %>
        <div class="sign-up-btn">
          <%= link_to "Create a fundraiser", new_fundraiser_path, class: "navbar-GroupAction-item-item navbar-GroupAction-item-link hvr-grow" %>
        </div>
      <% else %>
        <div class="sign-up-btn">
          <p>thing 1</p>
        </div>
      <% end %>
    </div>

    <div>
      <% if !user_signed_in? %>
        <div class="sign-up-btn">
          <%= link_to t(".sign_in", default: "Sign up as a User"), new_user_registration_path(is_charity: false), class: "navbar-GroupAction-item-item navbar-GroupAction-item-link hvr-grow" %>
        </div>
        <% else %>
          <div class="sign-up-btn">
            <p>thing 2</p>
          </div>
        <% end %>
    </div>

    </div>

  </div>






  <!-- Logo -->
  <div class="navbar-GroupAction-sides text-center">
    <div>
      <%= link_to root_path, class: "navbar-GroupAction-brand hidden-xs" do %>
        <%= image_tag "ga-logo.png" %>
      <% end %>
    </div>
  </div>

  <!-- end logo -->


  <!-- end of left side -->

  <!-- right side of navbar -->
  <div class="right-side-navbar">
    <div class="navbar-GroupAction-sides hidden-xs hidden-sm">
      <!-- <div class="navbar-GroupAction-item navbar-GroupAction-link">
        <%# if user_signed_in? %>
          <div class="navbar-GroupAction-item">
          PLAYER MENU
            <%#= link_to "player", "#", class: "hvr-grow toggle-player" %>
          </div>
        <%# end %>
      </div> -->
      <!-- PROFILE -->
      <div class="navbar-GroupAction-item navbar-GroupAction-link">

      </div>
      <div class="navbar-GroupAction-item navbar-GroupAction-link">
        <% if user_signed_in? %>
        <!-- MESSAGES -->

        <% end %>
      </div>
    </div>
  </div>

<div>

        <% if !user_signed_in? %>
      <div class="sign-in-btn">
        <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-GroupAction-item-item navbar-GroupAction-item-link hvr-grow" %>
      </div>
      <% else %>
        <div class="sign-in-btn no-wrap">
        <%= link_to "log out", destroy_user_session_path, method: :delete, class: "navbar-GroupAction-item-item navbar-GroupAction-item-link hvr-grow" %>
      </div>
    <% end %>

</div>


  <!-- Dropdown list appearing on mobile only -->


</div>