config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Attachinary::Engine => "/attachinary"

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # resources :fundraisers, only: [:index, :new, :create, :show, :edit, :update] do
  #   resources :direct_donations, only: [:index, :new, :create, :show, :edit, :update]
  #   resources :events, only: [:index, :new, :create, :show, :edit, :update] do
  #     resources :event_donations, only: [:new, :create, :show]
  #   end
  # end

  resources :fundraisers, only: [:index, :new, :create, :show, :edit, :update] do
    resources :fundraiser_updates, except: [:index]
    resources :fundraiser_videos, except: [:index, :show]
    resources :direct_donations, only: [:index, :new, :create, :show]
    resources :offline_donations, except: [:index, :show]
    resources :events do
      delete "/fundraisers/:fundraiser_id/events/:id", to: "events#destroy", as: "event_destroy"
      resources :event_donations, only: [:new, :create, :show]
      resources :event_videos, except: [:index, :show]
      resources :event_updates, except: [:index]
      resources :offline_donations, except: [:index, :show]
    end
  end

  resources :charities, except: [:destroy]
  get "about_us", to: 'pages#about_us'
  get "help", to: 'pages#help'
  get "contact_us", to: 'pages#contact_us'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/charity.rb
class Charity < ApplicationRecord
  belongs_to :user
  has_attachments :photos, maximum: 5

  def total_raised
    self.amount_raised = 0
    self.user.fundraisers.each { |fundraiser| self.amount_raised += fundraiser.total_raised unless fundraiser.total_raised.nil? }
    self.amount_raised
  end

  def number_donations
    no_donations = 0
    self.user.fundraisers.each do  |fundraiser|
      no_donations += fundraiser.direct_donations.count
      fundraiser.events.each { |event| no_donations += event.event_donations.count }
    end
    no_donations
  end

end

app/models/direct_donation.rb
class DirectDonation < ApplicationRecord
  belongs_to :user
  belongs_to :fundraiser
end

app/models/direct_dontation.rb
class DirectDontation < ApplicationRecord
  belongs_to :user
  belongs_to :fundraising_event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  belongs_to :fundraiser
  validates :target, presence: true
  has_many :event_donations
  has_many :event_videos
  has_many :event_updates
  has_many :offline_donations, as: :imageable
  has_attachments :photos, maximum: 5


  def total_raised
    self.amount_raised = 0
    self.event_donations.each { |donation| self.amount_raised += donation.amount }
    self.offline_donations.each { |donation| self.amount_raised += donation.amount}
    self.amount_raised
  end

end

app/models/event_donation.rb
class EventDonation < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event_update.rb
class EventUpdate < ApplicationRecord
  belongs_to :event
  has_attachments :photos, maximum: 5

  def video_url
    url = self.link.split("v=")[1]
    return url
  end

end

app/models/event_video.rb
class EventVideo < ApplicationRecord
  belongs_to :event

  def video_url
    url = self.link.split("v=")[1]
    return url
  end

end

app/models/fundraiser.rb
class Fundraiser < ApplicationRecord
  belongs_to :user
  has_many :events
  has_many :direct_donations
  has_many :fundraiser_videos
  has_many :fundraiser_updates
  has_many :offline_donations, as: :imageable
  validates :goal, inclusion: { in: ['Raise Money', 'Find Volunteers'], message: "%{value} is not a valid selection" }
  validates :label, inclusion: { in: ['People', 'Planet', 'Dignity'], message: "%{value} is not a valid selection" }
  has_attachments :photos, maximum: 5

  #has_many :event_donations, through: :event

  def total_raised
    self.amount_raised = 0
    self.direct_donations.each { |donation| self.amount_raised += donation.amount }
    self.offline_donations.each { |donation| self.amount_raised += donation.amount }
    self.events.each { |event| self.amount_raised += event.total_raised }
    self.amount_raised
  end

end

app/models/fundraiser_update.rb
class FundraiserUpdate < ApplicationRecord
  belongs_to :fundraiser
  has_attachments :photos, maximum: 5


  def video_url
    url = self.link.split("v=")[1]
    return url
  end

end

app/models/fundraiser_video.rb
class FundraiserVideo < ApplicationRecord
  belongs_to :fundraiser


  def video_url
    url = self.link.split("v=")[1]
    return url
  end


end

app/models/fundraising_event.rb
class FundraisingEvent < ApplicationRecord
  belongs_to :user
  has_many :events
  has_many :direct_donations
  has_many :event_donations, through: :event
end

app/models/offline_donation.rb
class OfflineDonation < ApplicationRecord
  belongs_to :imageable, polymorphic: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :event_donations
  has_many :direct_donations
  has_many :events
  has_many :fundraisers
  has_one :charity

  after_create :send_welcome_email

  devise :omniauthable, omniauth_providers: [:facebook]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params[:friend_uids] = auth.extra.raw_info.friends.data.map(&:id) if !auth.extra.raw_info.friends.data.nil?
    user_params = user_params.to_h

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end


  private

  def send_welcome_email
    UserMailer.welcome(self).deliver_now
  end

end

app/models/volunteer.rb
class Volunteer < ApplicationRecord
  belongs_to :user
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :set_fundraiser, only: [:new, :create, :show]

  def index
    @events = policy_scope(Event).order(:updated_at)
    authorize @events
  end

  def new
    @event = Event.new
    authorize @event
  end

  def create
    @event = Event.create(event_params)
    authorize @event

    @event.user = current_user
    @event.fundraiser = @fundraiser

    if @event.save
      redirect_to fundraiser_event_path(@fundraiser, @event)
    else
      render :new
    end
  end

  def show
    authorize @event
  end

  def edit
    authorize @event
  end

  def update
    authorize @event
    if @event.update(event_params)
      redirect_to fundraiser_event_path(@fundraiser, @event)
    else
      render :new
    end
  end

  def destroy
    authorize @event
    if @event.update(active: false)
      redirect_to fundraiser_event_path
    else
      render :new
    end
  end

  private

  def set_fundraiser
    @fundraiser = Fundraiser.find(params[:fundraiser_id])
  end


  def set_event
    # @event = params[:event_id].present? ? Event.find(params[:event_id]) : Event.find(params[:id])

    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:user_id, :fundraiser_id, :title, :start_date, :target, photos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charitys_helper.rb
module CharitysHelper
end

app/helpers/event_videos_helper.rb
module EventVideosHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/fundraisers_helper.rb
module FundraisersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/volunteer_helper.rb
module VolunteerHelper
end

app/views/events/_form.html.erb
<%= simple_form_for [@fundraiser, @event] do |f| %>
<%= render 'shared/error_messages', object: f.object %>
  <%= f.input :title %>
  <%= f.input :target %>
  <%= f.input :start_date %>
  <%= f.input :photos, as: :attachinary %>
  <%= f.submit %>
<% end %>

app/views/events/edit.html.erb
<div class="container">
  <%= render 'form' %>
</div>

app/views/events/index.html.erb
<% @events.each do |event| %>
  <%= event.title %>

    <% if user_signed_in? %>
      <p>
        <% if current_user.friend_uids.include?(event.user.uid) %>
        Your friend <%= event.user.first_name %> is hosting this event
        <% end %>
      </p>

      <!-- Donations made by friends to the event -->
      <% event.event_donations.each do |donation| %>
        <% if current_user.friend_uids.include?(donation.user.uid) %>
          <p>
            Your friend <%= donation.user.first_name %> donated to this event
          </p>
        <% end %>
      <% end %>

    <% end %>

<% end %>

app/views/events/show.html.erb
<div class="container">

<!-- link back to the fundraiser -->
  <%= link_to "back to fundraiser", fundraiser_path(@event.fundraiser) %>

  <!-- Delete button is only shown if no donations are present & current user is event owner -->
  <% if @event.event_donations.empty? && @event.user == current_user %>
    <%= link_to "Delete", fundraiser_event_event_destroy_path(@fundraiser, @event), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
  <% end %>


  <!-- basic information -->
  <div class="row" style="border-bottom: 1px solid #800020; padding-bottom: 30px;">
    <h1 class="thin-header"> </h1>

    <h1>
      <%= @event.title %>
    </h1>

    <% if user_signed_in? && current_user.friend_uids.include?(@event.user.uid) %>
      <h2>
        <%= "hosted by your friend #{@event.user.first_name}" %>
      </h2>
    <% end %>
     <div class="col-xs-12 col-md-6" style="padding-top: 30px">
        <%= image_tag "library/baby.jpg", class: "half-page-image" %>
    </div>

  <div class="col-xs-12 col-md-6">
      <!-- basic information -->
      <div>
        <h2>
          <span class="off-complimentary">£<%= @event.total_raised.ceil %></span> of <span class="off-complimentary">£<%= @event.target.ceil %></span> raised so far
        </h2>
        <h2>
        </h2>
        <% unless @event.start_date.nil? %>
        <h5>Starting <%= @event.start_date.strftime("%e %B %Y") %></h5>
        <% end %>
        <div id="donor_counter"></div>
        <div class="text-center">
         <button type="button" class="big-button btn btn-lg hvr-grow" data-toggle="modal" data-target="#donateModal">Donate</button>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="donateModal" tabindex="-1" role="dialog" aria-labelledby="donateModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="donateModalLabel">Donate</h4>
        </div>
        <!-- direct donations -->
        <div class="modal-body">
          <%= render 'event_donations/form', fundraiser: @fundraiser, event: @event, event_donation: EventDonation.new %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-md-6">
      <!-- Offline donations -->
      <div class="some-padding">
        <h2 class="brand-color" style="font-weight: lighter" >Offline Donations <i class="fa fa-question-circle-o" style="font-size: 25px" aria-hidden="true" data-toggle="tooltip" data-placement="right" title="Donations given outside Group Action"></i></h2>
        <!-- if page owner can create/edit offline donations -->
      <% if @event.user == current_user %>
        <%= link_to "Record an offline donation", new_fundraiser_event_offline_donation_path(@fundraiser, @event), class: "btn btn-primary", style: "margin-bottom: 15px" %>
      <% end %>

    <!-- total raised (shitty formula I know) -->
      <% event_offline_donation = 0 %>
      <p style="font-size: 20px"> Total raised offline: <% @event.offline_donations.each do |donation| %>
        <% event_offline_donation += donation.amount %>
        <% end %>
        <span style="color: #BD2F53">£<%= event_offline_donation.ceil %> </span>
      </p>
    <!-- offline donation comments -->
        <h3 style="font-weight: lighter; color: #800020">Previous offline donations</h3>
        <% @event.offline_donations.each do |donation| %>
          <p class="underlined"> <span class="bold-off-brand">£<%= donation.amount.ceil %> </span> | <%= donation.message %>
          <% if @event.user == current_user %>
          <span class="float-right">
            <%= link_to "edit", edit_fundraiser_event_offline_donation_path(@fundraiser, @event, donation) %>
            <%= link_to "delete", fundraiser_event_offline_donation_path(@fundraiser, @event, donation), data: { confirm: "Are you sure?" }, method: :delete %>
            </span>
          <% end %>
          </p>
        <% end %>
      </div>
    </div>

    <div class="col-xs-12 col-md-6">
      <!-- Prior event donations -->
      <h2>Prior event donations</h2>
        <% @event.event_donations.each do |donation| %>
          <% if (donation.message == "")
              message = "no message"
            else
              message = donation.message
           end %>
          <p>
             <span class="bold-off-brand">£<%= donation.amount.ceil %> </span> | <%= message %>
             <span class="float-right"> <%= user_signed_in? && current_user.friend_uids.include?(donation.user.uid) ? "your friend #{donation.user.first_name}" : donation.user.email %> </span>
          </p>
      <% end %>
    </div>
  </div>


    <!-- youtube -->
<div class="section-seperator">
  <h1> Youtube videos!</h1>
    <% @event.event_videos.each do |video| %>
      <div>
       <h2> <%=  video.title  %> <%= link_to "edit", edit_fundraiser_event_event_video_path(@fundraiser, @event, video) %> <%= link_to "destroy", fundraiser_event_event_video_path(@fundraiser, @event, video), method: 'delete', :data => {:confirm => 'Are you sure?'} %> </h2>
        <iframe id="ytplayer" type="text/html" width="640" height="360"
      src="https://www.youtube.com/embed/<%=video.video_url%>?autoplay=0&origin=http://example.com"
      frameborder="0"></iframe>
      </div>
      <% end %>

<!-- If owner of the site add a video -->
  <% if @event.user == current_user %>
    <%= link_to "Add a new video", new_fundraiser_event_event_video_path(@fundraiser, @event), class: "btn btn-primary" %>
  <% end %>
</div>


  <!-- Updates! -->
<div class="section-seperator">
  <h1> Updates</h1>
    <% @event.event_updates.each do |update| %>
      <div>
        <h2> <%= update.title %>  <%= link_to "edit", edit_fundraiser_event_event_update_path(@fundraiser, @event, update) %> <%= link_to "destroy", fundraiser_event_event_update_path(@fundraiser, @event, update), method: 'delete', :data => {:confirm => 'Are you sure?'} %> </h2>
        <p> <%= update.message %></p>
        <p> <%= link_to "see more of this update", fundraiser_event_event_update_path(@fundraiser, @event, update)  %></p>
      </div>
    <% end %>


  <!-- If ownder of the event add an update -->
    <% if @event.user == current_user %>
    <%= link_to "Add a new update", new_fundraiser_event_event_update_path(@fundraiser, @event), class: "btn btn-primary" %>
  <% end %>
</div>

</div>


<%= content_for(:after_js) do %>
  <script>
    $(document).ready(function(){
      $('#donor_counter').goalProgress({
        goalAmount: <%= @event.target %>,
        currentAmount: <%= @event.total_raised %>,
        textBefore: '£',
        textAfter: ' raised'
      });
    });
  </script>
<% end %>