config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Attachinary::Engine => "/attachinary"

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # resources :fundraisers, only: [:index, :new, :create, :show, :edit, :update] do
  #   resources :direct_donations, only: [:index, :new, :create, :show, :edit, :update]
  #   resources :events, only: [:index, :new, :create, :show, :edit, :update] do
  #     resources :event_donations, only: [:new, :create, :show]
  #   end
  # end

  resources :fundraisers, only: [:index, :new, :create, :show, :edit, :update] do
    resources :fundraiser_updates, except: [:index]
    resources :fundraiser_videos, except: [:index, :show]
    resources :direct_donations, only: [:index, :new, :create, :show]
    resources :offline_donations, except: [:index, :show]
    resources :events do
      delete "/fundraisers/:fundraiser_id/events/:id", to: "events#destroy", as: "event_destroy"
      resources :event_donations, only: [:new, :create, :show]
      resources :event_videos, except: [:index, :show]
      resources :event_updates, except: [:index]
      resources :offline_donations, except: [:index, :show]
    end
  end

  resources :charities, except: [:destroy]
  get "about_us", to: 'pages#about_us'
  get "help", to: 'pages#help'
  get "contact_us", to: 'pages#contact_us'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/charity.rb
class Charity < ApplicationRecord
  belongs_to :user
  has_attachments :photos, maximum: 5

  def total_raised
    self.amount_raised = 0
    self.user.fundraisers.each { |fundraiser| self.amount_raised += fundraiser.total_raised unless fundraiser.total_raised.nil? }
    self.amount_raised
  end

  def number_donations
    no_donations = 0
    self.user.fundraisers.each do  |fundraiser|
      no_donations += fundraiser.direct_donations.count
      fundraiser.events.each { |event| no_donations += event.event_donations.count }
    end
    no_donations
  end

end

app/models/direct_donation.rb
class DirectDonation < ApplicationRecord
  belongs_to :user
  belongs_to :fundraiser
end

app/models/direct_dontation.rb
class DirectDontation < ApplicationRecord
  belongs_to :user
  belongs_to :fundraising_event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  belongs_to :fundraiser
  validates :target, presence: true
  has_many :event_donations
  has_many :event_videos
  has_many :event_updates
  has_many :offline_donations, as: :imageable
  has_attachments :photos, maximum: 5


  def total_raised
    self.amount_raised = 0
    self.event_donations.each { |donation| self.amount_raised += donation.amount }
    self.offline_donations.each { |donation| self.amount_raised += donation.amount}
    self.amount_raised
  end

end

app/models/event_donation.rb
class EventDonation < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event_update.rb
class EventUpdate < ApplicationRecord
  belongs_to :event
  has_attachments :photos, maximum: 5

  def video_url
    url = self.link.split("v=")[1]
    return url
  end

end

app/models/event_video.rb
class EventVideo < ApplicationRecord
  belongs_to :event

  def video_url
    url = self.link.split("v=")[1]
    return url
  end

end

app/models/fundraiser.rb
class Fundraiser < ApplicationRecord
  belongs_to :user
  has_many :events
  has_many :direct_donations
  has_many :fundraiser_videos
  has_many :fundraiser_updates
  has_many :offline_donations, as: :imageable
  validates :goal, inclusion: { in: ['Raise Money', 'Find Volunteers'], message: "%{value} is not a valid selection" }
  validates :label, inclusion: { in: ['People', 'Planet', 'Dignity'], message: "%{value} is not a valid selection" }
  has_attachments :photos, maximum: 5

  #has_many :event_donations, through: :event

  def total_raised
    self.amount_raised = 0
    self.direct_donations.each { |donation| self.amount_raised += donation.amount }
    self.offline_donations.each { |donation| self.amount_raised += donation.amount }
    self.events.each { |event| self.amount_raised += event.total_raised }
    self.amount_raised
  end

end

app/models/fundraiser_update.rb
class FundraiserUpdate < ApplicationRecord
  belongs_to :fundraiser
  has_attachments :photos, maximum: 5


  def video_url
    url = self.link.split("v=")[1]
    return url
  end

end

app/models/fundraiser_video.rb
class FundraiserVideo < ApplicationRecord
  belongs_to :fundraiser


  def video_url
    url = self.link.split("v=")[1]
    return url
  end


end

app/models/fundraising_event.rb
class FundraisingEvent < ApplicationRecord
  belongs_to :user
  has_many :events
  has_many :direct_donations
  has_many :event_donations, through: :event
end

app/models/offline_donation.rb
class OfflineDonation < ApplicationRecord
  belongs_to :imageable, polymorphic: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :event_donations
  has_many :direct_donations
  has_many :events
  has_many :fundraisers
  has_one :charity

  after_create :send_welcome_email

  devise :omniauthable, omniauth_providers: [:facebook]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params[:friend_uids] = auth.extra.raw_info.friends.data.map(&:id) if !auth.extra.raw_info.friends.data.nil?
    user_params = user_params.to_h

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end


  private

  def send_welcome_email
    UserMailer.welcome(self).deliver_now
  end

end

app/models/volunteer.rb
class Volunteer < ApplicationRecord
  belongs_to :user
end

app/controllers/charities_controller.rb
class CharitiesController < ApplicationController

  before_action :set_charity, only: [:show, :edit, :update, :destroy]

  def index
    @charities = policy_scope(Charity).order(:updated_at)
    authorize @charities
  end

  def new
    @charity = Charity.new
    authorize @charity
  end

  def create
    @charity = Charity.create(charity_params)
    @charity.user = current_user
    @charity.amount_raised = @charity.total_raised
    authorize @charity

    if @charity.save
      redirect_to charity_path(@charity)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @charity.update(charity_params)
      redirect_to charity_path(@charity)
    else
      render :new
    end
  end


  private

  def charity_params
    params.require(:charity).permit(:name, :mission, :bio, :charity_number, photos: [])
  end

  def set_charity
    @charity = Charity.find(params[:id])
    authorize @charity
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charitys_helper.rb
module CharitysHelper
end

app/helpers/event_videos_helper.rb
module EventVideosHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/fundraisers_helper.rb
module FundraisersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/volunteer_helper.rb
module VolunteerHelper
end

app/views/charities/_form.html.erb
<div class="donation_form">
<%= simple_form_for @charity do |f| %>
  <%= f.input :name %>
  <%= f.input :mission %>
  <%= f.input :bio %>
  <%= f.input :charity_number %>
  <%= f.input :photos, as: :attachinary %>
  <div class="text-center">
  <%= f.submit class: "btn-primary btn btn-lg" %>
  </div>
<% end %>
</div>

app/views/charities/index.html.erb
<div class="container">


<h2> Description of what it takes to be a charity on our website. How we believe these charities are the ones that are going to pioneer a new way of giving and fundraising </h2>

  <% @charities.each do |charity| %>
    <div class="row">
      <div class="col-xs-12">
        <div class="flexbox-space-btwn index-page">
          <div class="small-img">
           <%= cl_image_tag charity.photos.first.path %>
          </div>
          <div class="left-text" style="min-width: 30vw">
            <h2 class="brand-color"  style="font-weight: lighter"> <span class="underlined"><%= charity.name %></span>  </h2>
            <h3> <%= charity.mission.truncate_words(8) %> </h3>
            <p> <%= charity.bio.truncate_words(5) %> </p>
          </div>
          <div class="left-text">
            <h3> Ongoing fundraisers for this charity</h3>
              <% charity.user.fundraisers.each do |fundraiser| %>
              <%= link_to fundraiser.title, fundraiser_path(fundraiser) %>
            <% end %>
          </div>
          <%= link_to "", charity_path(charity), class: "card-link" %>
        </div>
      </div>

      <!-- card -->
     <!--  <div class="col-xs-4">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%#= image_path 'library/crowd.jpg' %>');">
        </div>
      </div> -->

      <!-- Body of Text -->
      <!-- <div class="col-xs-6">
        <h2> <%#= charity.name %> (name of charity) </h2>
        <h3> <%#= charity.mission.truncate_words(8) %> (mission of charity) </h3>
        <h4> <%#= charity.bio.truncate_words(5) %> (bio of charity) </h4>
      </div> -->

      <!-- <div class="col-xs-2">
        <h4> Fundraisers being ran for this charity!</h4>
          <%# charity.user.fundraisers.each do |fundraiser| %>
          <%#= link_to fundraiser.title, fundraiser_path(fundraiser) %>
        <%# end %>
      </div> -->





      <%#= link_to "", charity_path(charity), class: "card-link" %>
    </div>
  <% end %>

</div>

app/views/charities/new.html.erb
<div class="container">
  <%= render 'form' %>
</div>

app/views/charities/show.html.erb
<div id="home-banner" style="background-image: linear-gradient(-225deg, rgba(0, 0, 0, 0.4) 0%, rgba(0, 0, 0, 0.5)), url('<%= cl_image_path @charity.photos.first.path %>'); background-size: cover; background-position: center; background-attachment: fixed;">
  <div class="text-center" style="color: white; text-shadow: 1px 1px 2px grey;">
    <h1> <span class="off-complimentary" style="text-shadow: 1px 1px 2px #34353A;"><%= @charity.name  %></span> is making a difference today</h1>

    <!-- Money raised -->
    <h3> £<%= @charity.total_raised.ceil %> raised from <%= @charity.number_donations %> donations </h3>

    <!-- edit -->
    <% if @charity.user == current_user %>
      <h3 class="off-complimentary-link opacity-link"> <%= link_to "edit", edit_charity_path %> </h3>
    <% end %>

  </div>
</div>

<!-- REMINDER TO SELF: CHANGE THIS TO A H2 HEADING (ABOUT) WITH TWO COL-SM-6 FOR 'BIO' AND 'MISSION' -->

<div class="container">
  <div class="row">
    <div class="text-center"><h2 style="font-weight: lighter">About <%= @charity.name %></h2></div>
    <div class="col-sm-6">
      <!-- Bio -->
      <div class="outlined-box" style="margin-top: 30px">
        <h3 style="font-weight: lighter; margin-top: 0px" class="text-center">Bio</h3>
        <p class="brand-color"> <%=  @charity.bio  %> </p>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="outlined-box" style="margin-top: 30px">
        <h3 style="font-weight: lighter; margin-top: 0px" class="text-center">Our Mission</h3>
        <p class="brand-color"> <%= @charity.mission %>  </p>
      </div>
    </div>
  </div>



  <!-- photos v2 -->
  <div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls">
      <div class="slides"></div>
      <h3 class="title"></h3>
      <a class="prev">‹</a>
      <a class="next">›</a>
      <a class="close">×</a>
      <a class="play-pause"></a>
      <ol class="indicator"></ol>
  </div>

  <div id="links">
  <h2> Photos</h2>
    <% @charity.photos.each do |photo| %>
      <%= link_to cl_image_path photo.path do %>
         <%= cl_image_tag photo.path, width: 300, crop: :fill, class: "gallery-image"%>
      <% end %>
    <% end %>
  </div>

  <!-- list of charity fundraisers -->
  <h2>Fundraisers</h2>
  <div class="row">
    <% @charity.user.fundraisers.each do |fundraiser| %>
      <div class="col-xs-4">
      <p> <%= fundraiser.title  %> </p>
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image_path 'library/crowd.jpg' %>');">
          <%= link_to "", fundraiser_path(fundraiser), class: "card-link" %>
        </div>
      </div>
    <% end %>
  </div>
</div>
  <!-- script for the images -->

<%= content_for(:after_js) do %>
  <script>
  document.getElementById('links').onclick = function (event) {
      event = event || window.event;
      var target = event.target || event.srcElement,
          link = target.src ? target.parentNode : target,
          options = {index: link, event: event},
          links = this.getElementsByTagName('a');
      blueimp.Gallery(links, options);
  };
  </script>
<% end %>